version: '3'
services:
  grapher:
    build: .
    ports:
      - "8080:8080"
    environment:
      SNMP_HOST: "localhost"
      SNMP_COMMUNITY: "public"
      SNMP_OID: ".1.3.6.1.2.1.1.3.0"
      POLL_INTERVAL: "1m"
      DB_PATH: "/data/data.db"
    volumes:
      - data:/data
volumes:
  data:
