version: '3'
services:
  grapher:
    build: .
    ports:
      - "8088:8080"
    environment:
      CONFIG_PATH: "/app/config.json"
      POLL_INTERVAL: "1m"
      DB_PATH: "/data/data.db"
    volumes:
      - data:/data
      - ./config.json:/app/config.json:ro
volumes:
  data:
